import type { ProjectConfiguration } from "@astro-stack/utils";
import type { FeatureTemplate } from "../contracts.js";
import { defineFeature } from "../define-feature.js";

function agentInstructionTemplate(
  configuration: ProjectConfiguration,
  agent: "codex" | "claude",
): FeatureTemplate {
  const shared = `# Project instructions\n\nThis is an Astro project generated by Astro Stack. Keep the generated project independent of Astro Stack, prefer Astro's official capabilities, and run the selected project checks before handing work off.\n\n## Tooling\n\n- TypeScript: ${configuration.styling.typescript}\n- ESLint: ${configuration.styling.eslint ? "selected" : "not selected"}\n- Prettier: ${configuration.styling.prettier ? "selected" : "not selected"}\n- Biome: ${configuration.styling.biome ? "selected" : "not selected"}\n`;
  return {
    destination: agent === "codex" ? "AGENTS.md" : "CLAUDE.md",
    content: `<!-- astro-stack agent instructions v1 -->\n\n${shared}`,
  };
}

function vscodeTemplates(
  configuration: ProjectConfiguration,
): readonly FeatureTemplate[] {
  const extensions = [
    "astro-build.astro-vscode",
    ...(configuration.styling.eslint ? ["dbaeumer.vscode-eslint"] : []),
    ...(configuration.styling.prettier ? ["esbenp.prettier-vscode"] : []),
    ...(configuration.styling.biome ? ["biomejs.biome"] : []),
  ];
  return [
    {
      destination: ".vscode/settings.json",
      content: `${JSON.stringify({ "editor.formatOnSave": configuration.styling.prettier || configuration.styling.biome, "editor.codeActionsOnSave": configuration.styling.eslint ? { "source.fixAll.eslint": "explicit" } : {} }, null, 2)}\n`,
    },
    {
      destination: ".vscode/extensions.json",
      content: `${JSON.stringify({ recommendations: extensions }, null, 2)}\n`,
    },
  ];
}

function zedTemplates(
  configuration: ProjectConfiguration,
): readonly FeatureTemplate[] {
  const formatOnSave =
    configuration.styling.prettier || configuration.styling.biome
      ? "on"
      : "off";
  return [
    {
      destination: ".zed/settings.json",
      content: `${JSON.stringify({ languages: { Astro: { format_on_save: formatOnSave }, JavaScript: { format_on_save: formatOnSave }, TypeScript: { format_on_save: formatOnSave } } }, null, 2)}\n`,
    },
  ];
}

export const developerExperienceFeatures = [
  ...(["codex", "claude"] as const).map((agent) =>
    defineFeature({
      id: `developer-experience:agent:${agent}`,
      selection: {
        group: "developerExperience.agents",
        value: agent,
        label:
          agent === "codex" ? "Codex (AGENTS.md)" : "Claude Code (CLAUDE.md)",
      },
      isSelected: (configuration) =>
        configuration.developerExperience.agents.includes(agent),
      contributions: {
        templates: (configuration) => [
          agentInstructionTemplate(configuration, agent),
        ],
      },
    }),
  ),
  ...(["vscode", "cursor"] as const).map((editor) =>
    defineFeature({
      id: `developer-experience:editor:${editor}`,
      selection: {
        group: "developerExperience.editors",
        value: editor,
        label: editor === "vscode" ? "VS Code" : "Cursor",
      },
      isSelected: (configuration) =>
        configuration.developerExperience.editors.includes(editor),
      ...(editor === "vscode"
        ? {
            incompatibleWith: [
              {
                featureId: "developer-experience:editor:cursor",
                code: "incompatible-editor-targets",
                path: "developerExperience.editors",
                message:
                  "VS Code and Cursor cannot be selected together because both own .vscode workspace configuration.",
                suggestion: "Choose either vscode or cursor.",
              },
            ],
          }
        : {}),
      contributions: { templates: vscodeTemplates },
    }),
  ),
  defineFeature({
    id: "developer-experience:editor:zed",
    selection: {
      group: "developerExperience.editors",
      value: "zed",
      label: "Zed",
    },
    isSelected: (configuration) =>
      configuration.developerExperience.editors.includes("zed"),
    contributions: { templates: zedTemplates },
  }),
] as const;
