import type {
  ConfigurationIssue,
  ProjectConfiguration,
} from "@astro-stack/utils";
import type {
  FeatureConfigurationChange,
  FeatureConflict,
  FeatureDefinition,
  FeatureDependency,
  FeatureLifecycleHooks,
  FeatureResolution,
  FeatureTemplate,
} from "./contracts.js";

export type {
  AstroConfigExpression,
  FeatureConfigurationChange,
  FeatureConflict,
  FeatureDefinition,
  FeatureDependency,
  FeatureLifecycleContext,
  FeatureLifecycleHooks,
  FeatureResolution,
  FeatureTemplate,
} from "./contracts.js";

function selectedFeature(
  id: string,
  isSelected: FeatureDefinition["isSelected"],
  options: Omit<FeatureDefinition, "id" | "isSelected"> = {},
): FeatureDefinition {
  return { id, isSelected, ...options };
}

function selectionIssue(
  code: string,
  path: string,
  message: string,
  suggestion?: string,
): ConfigurationIssue {
  return {
    level: "error",
    code,
    path,
    message,
    ...(suggestion ? { suggestion } : {}),
  };
}

const contentConfigTemplate = {
  destination: "src/content.config.ts",
  content:
    'import { defineCollection } from "astro:content";\nimport { glob } from "astro/loaders";\n\nconst posts = defineCollection({\n  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/posts" }),\n});\n\nexport const collections = { posts };\n',
};

const contactFormTemplate: FeatureTemplate = {
  destination: "src/components/ContactForm.astro",
  content:
    '---\nconst endpoint = "/api/contact";\n---\n\n<form action={endpoint} method="post" data-contact-form>\n  <p>\n    <label>\n      Name (optional)\n      <input name="name" autocomplete="name" />\n    </label>\n  </p>\n  <p>\n    <label>\n      Email\n      <input name="email" type="email" autocomplete="email" required />\n    </label>\n  </p>\n  <p>\n    <label>\n      Message\n      <textarea name="message" rows="6" required></textarea>\n    </label>\n  </p>\n  <button type="submit">Send message</button>\n  <p aria-live="polite" data-contact-status></p>\n</form>\n\n<script>\n  const form = document.querySelector<HTMLFormElement>("[data-contact-form]");\n  const status = document.querySelector<HTMLElement>("[data-contact-status]");\n\n  form?.addEventListener("submit", async (event) => {\n    event.preventDefault();\n    if (!status) return;\n    status.textContent = "Sending…";\n\n    try {\n      const response = await fetch(form.action, {\n        method: "POST",\n        body: new FormData(form),\n        headers: { Accept: "application/json" },\n      });\n      if (!response.ok) throw new Error("Unable to send the message.");\n      form.reset();\n      status.textContent = "Thanks — your message has been sent.";\n    } catch {\n      status.textContent = "Unable to send your message. Please try again.";\n    }\n  });\n</script>\n',
};

const agentInstructionTemplates = (
  configuration: ProjectConfiguration,
): readonly FeatureTemplate[] => {
  const shared = `# Project instructions\n\nThis is an Astro project generated by Astro Stack. Keep the generated project independent of Astro Stack, prefer Astro's official capabilities, and run the selected project checks before handing work off.\n\n## Tooling\n\n- TypeScript: ${configuration.styling.typescript}\n- ESLint: ${configuration.styling.eslint ? "selected" : "not selected"}\n- Prettier: ${configuration.styling.prettier ? "selected" : "not selected"}\n- Biome: ${configuration.styling.biome ? "selected" : "not selected"}\n`;
  return [
    ...(configuration.developerExperience.agents.includes("codex")
      ? [
          {
            destination: "AGENTS.md",
            content: `<!-- astro-stack agent instructions v1 -->\n\n${shared}`,
          },
        ]
      : []),
    ...(configuration.developerExperience.agents.includes("claude")
      ? [
          {
            destination: "CLAUDE.md",
            content: `<!-- astro-stack agent instructions v1 -->\n\n${shared}`,
          },
        ]
      : []),
  ];
};

const editorTemplates = (
  configuration: ProjectConfiguration,
): readonly FeatureTemplate[] => {
  const extensions = [
    "astro-build.astro-vscode",
    ...(configuration.styling.eslint ? ["dbaeumer.vscode-eslint"] : []),
    ...(configuration.styling.prettier ? ["esbenp.prettier-vscode"] : []),
    ...(configuration.styling.biome ? ["biomejs.biome"] : []),
  ];
  const vscodeTemplates = [
    {
      destination: ".vscode/settings.json",
      content: `${JSON.stringify({ "editor.formatOnSave": configuration.styling.prettier || configuration.styling.biome, "editor.codeActionsOnSave": configuration.styling.eslint ? { "source.fixAll.eslint": "explicit" } : {} }, null, 2)}\n`,
    },
    {
      destination: ".vscode/extensions.json",
      content: `${JSON.stringify({ recommendations: extensions }, null, 2)}\n`,
    },
  ];
  const zedTemplates = [
    {
      destination: ".zed/settings.json",
      content: `${JSON.stringify({ languages: { Astro: { format_on_save: configuration.styling.prettier || configuration.styling.biome ? "on" : "off" }, JavaScript: { format_on_save: configuration.styling.prettier || configuration.styling.biome ? "on" : "off" }, TypeScript: { format_on_save: configuration.styling.prettier || configuration.styling.biome ? "on" : "off" } } }, null, 2)}\n`,
    },
  ];
  return [
    ...((["vscode", "cursor"] as const).some((editor) =>
      configuration.developerExperience.editors.includes(editor),
    )
      ? vscodeTemplates
      : []),
    ...(configuration.developerExperience.editors.includes("zed")
      ? zedTemplates
      : []),
  ];
};

/**
 * The framework-neutral visual baseline for generated sites. Styling choices
 * change how a project is authored, not the appearance of its starter pages.
 */
const starterSiteStyles = `:root {
  font-family: Georgia, "Times New Roman", serif;
  color: #172033;
  background: #f8fafc;
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

body,
h1,
h2,
h3,
p,
ul {
  margin: 0;
}

body {
  min-width: 20rem;
  background: #f8fafc;
}

a {
  color: #0f766e;
  text-decoration-thickness: 0.08em;
  text-underline-offset: 0.16em;
}

h1,
h2,
h3 {
  font-family: ui-sans-serif, system-ui, sans-serif;
  font-weight: 700;
  letter-spacing: -0.03em;
}

header,
nav,
main,
footer {
  width: min(100% - 2rem, 72rem);
  margin-inline: auto;
}

header {
  padding-block: 1.5rem;
  border-bottom: 1px solid color-mix(in srgb, #172033 15%, transparent);
  font-family: ui-sans-serif, system-ui, sans-serif;
  font-weight: 700;
}

nav {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
  padding-block: 1rem;
  font-family: ui-sans-serif, system-ui, sans-serif;
}

main {
  padding-block: clamp(3rem, 8vw, 6rem);
}

main > * + * {
  margin-top: 3rem;
}

article,
section {
  max-width: 44rem;
}

article > * + *,
section > * + * {
  margin-top: 1rem;
}

h1 {
  max-width: 12ch;
  font-size: clamp(2.5rem, 7vw, 5rem);
  line-height: 0.95;
}

h2 {
  font-size: clamp(1.5rem, 4vw, 2.25rem);
  line-height: 1.1;
}

p,
li {
  font-size: 1.0625rem;
  line-height: 1.7;
}

ul {
  padding-left: 1.25rem;
}

footer {
  padding-block: 2rem;
  border-top: 1px solid color-mix(in srgb, #172033 15%, transparent);
  color: color-mix(in srgb, #172033 65%, transparent);
}
`;

/**
 * The complete initial registry. Each feature owns the files, dependencies,
 * and configuration it adds to a generated project.
 */
export const featureRegistry: readonly FeatureDefinition[] = [
  selectedFeature(
    "developer-experience:agent-instructions",
    (configuration) => configuration.developerExperience.agents.length > 0,
    { templates: agentInstructionTemplates },
  ),
  selectedFeature(
    "developer-experience:editor",
    (configuration) => configuration.developerExperience.editors.length > 0,
    { templates: editorTemplates },
  ),
  selectedFeature(
    "styling:vanilla",
    (configuration) => configuration.styling.css === "vanilla",
    {
      templates: [
        {
          destination: "src/styles/global.css",
          content: starterSiteStyles,
        },
      ],
    },
  ),
  selectedFeature(
    "styling:tailwind",
    (configuration) => configuration.styling.css === "tailwind",
    {
      dependencies: [
        { name: "@tailwindcss/vite", version: "^4.3.2", type: "devDependency" },
        { name: "tailwindcss", version: "^4.3.2", type: "devDependency" },
      ],
      templates: [
        {
          destination: "src/styles/global.css",
          content:
            '@import "tailwindcss";\n\n@theme {\n  --color-ink: #172033;\n  --color-paper: #f8fafc;\n  --color-accent: #0f766e;\n}\n\n@layer base {\n  :root {\n    font-family: Georgia, "Times New Roman", serif;\n    color: var(--color-ink);\n    background: var(--color-paper);\n  }\n\n  body {\n    min-width: 20rem;\n    margin: 0;\n    background: var(--color-paper);\n  }\n\n  a {\n    color: var(--color-accent);\n    text-decoration-thickness: 0.08em;\n    text-underline-offset: 0.16em;\n  }\n\n  h1,\n  h2,\n  h3 {\n    font-family: ui-sans-serif, system-ui, sans-serif;\n    font-weight: 700;\n    letter-spacing: -0.03em;\n  }\n}\n\n@layer components {\n  header,\n  nav,\n  main,\n  footer {\n    width: min(100% - 2rem, 72rem);\n    margin-inline: auto;\n  }\n\n  header {\n    padding-block: 1.5rem;\n    border-bottom: 1px solid color-mix(in srgb, var(--color-ink) 15%, transparent);\n    font-family: ui-sans-serif, system-ui, sans-serif;\n    font-weight: 700;\n  }\n\n  nav {\n    display: flex;\n    flex-wrap: wrap;\n    gap: 1rem;\n    padding-block: 1rem;\n    font-family: ui-sans-serif, system-ui, sans-serif;\n  }\n\n  main {\n    padding-block: clamp(3rem, 8vw, 6rem);\n  }\n\n  main > * + * {\n    margin-top: 3rem;\n  }\n\n  article,\n  section {\n    max-width: 44rem;\n  }\n\n  article > * + *,\n  section > * + * {\n    margin-top: 1rem;\n  }\n\n  h1 {\n    max-width: 12ch;\n    font-size: clamp(2.5rem, 7vw, 5rem);\n    line-height: 0.95;\n  }\n\n  h2 {\n    font-size: clamp(1.5rem, 4vw, 2.25rem);\n    line-height: 1.1;\n  }\n\n  p,\n  li {\n    font-size: 1.0625rem;\n    line-height: 1.7;\n  }\n\n  ul {\n    padding-left: 1.25rem;\n  }\n\n  footer {\n    padding-block: 2rem;\n    border-top: 1px solid color-mix(in srgb, var(--color-ink) 15%, transparent);\n    color: color-mix(in srgb, var(--color-ink) 65%, transparent);\n  }\n}\n',
        },
      ],
      configurationChanges: [
        {
          file: "astro.config.mjs",
          path: "vite.plugins",
          value: { type: "astro-config-expression", code: "[tailwindcss()]" },
          imports: ['import tailwindcss from "@tailwindcss/vite";'],
        },
      ],
    },
  ),
  ...(["strict", "relaxed"] as const).map((typescript) =>
    selectedFeature(
      `typescript:${typescript}`,
      (configuration) => configuration.styling.typescript === typescript,
    ),
  ),
  selectedFeature(
    "tooling:eslint",
    (configuration) => configuration.styling.eslint,
    {
      dependencies: [
        { name: "@eslint/js", version: "^10.0.1", type: "devDependency" },
        { name: "eslint", version: "^10.7.0", type: "devDependency" },
        {
          name: "eslint-plugin-astro",
          version: "^3.0.0",
          type: "devDependency",
        },
        { name: "globals", version: "^17.7.0", type: "devDependency" },
        {
          name: "typescript-eslint",
          version: "^8.64.0",
          type: "devDependency",
        },
      ],
      templates: [
        {
          destination: "eslint.config.js",
          content:
            'import js from "@eslint/js";\nimport astro from "eslint-plugin-astro";\nimport globals from "globals";\nimport tseslint from "typescript-eslint";\n\nexport default [\n  {\n    ignores: ["**/.astro/**", "**/dist/**", "**/.netlify/**", "**/.vercel/**", "**/.wrangler/**"],\n  },\n  js.configs.recommended,\n  ...tseslint.configs.recommended,\n  ...astro.configs.recommended,\n  {\n    files: ["**/*.{astro,js,mjs,cjs,ts,mts,cts}"],\n    languageOptions: {\n      globals: globals.browser,\n    },\n  },\n];\n',
        },
      ],
      configurationChanges: [
        {
          file: "package.json",
          path: "scripts.lint",
          value: "eslint .",
        },
        {
          file: "package.json",
          path: "scripts.lint:fix",
          value: "eslint . --fix",
        },
      ],
    },
  ),
  selectedFeature(
    "tooling:prettier",
    (configuration) => configuration.styling.prettier,
    {
      dependencies: [
        { name: "prettier", version: "^3.9.5", type: "devDependency" },
        {
          name: "prettier-plugin-astro",
          version: "^0.14.1",
          type: "devDependency",
        },
      ],
      templates: [
        {
          destination: ".prettierrc.json",
          content: '{\n  "plugins": ["prettier-plugin-astro"]\n}\n',
        },
        {
          destination: ".prettierignore",
          content:
            "node_modules/\ndist/\n.astro/\n.netlify/\n.vercel/\n.wrangler/\npnpm-lock.yaml\npackage-lock.json\nyarn.lock\nbun.lock\nbun.lockb\n",
        },
      ],
      configurationChanges: [
        {
          file: "package.json",
          path: "scripts.format",
          value: "prettier --write .",
        },
        {
          file: "package.json",
          path: "scripts.format:check",
          value: "prettier --check .",
        },
      ],
    },
  ),
  selectedFeature(
    "tooling:biome",
    (configuration) => configuration.styling.biome,
    {
      dependencies: [
        { name: "@biomejs/biome", version: "2.5.4", type: "devDependency" },
      ],
      templates: [
        {
          destination: "biome.json",
          content:
            '{\n  "$schema": "https://biomejs.dev/schemas/2.5.4/schema.json",\n  "files": {\n    "includes": [\n      "**",\n      "!!**/*.astro",\n      "!!**/.astro",\n      "!!**/dist",\n      "!!**/.netlify",\n      "!!**/.vercel",\n      "!!**/.wrangler"\n    ]\n  },\n  "css": {\n    "parser": {\n      "tailwindDirectives": true\n    }\n  },\n  "formatter": {\n    "enabled": true,\n    "indentStyle": "space"\n  },\n  "assist": {\n    "enabled": false\n  },\n  "linter": {\n    "enabled": true,\n    "rules": {\n      "preset": "recommended"\n    }\n  }\n}\n',
        },
      ],
      configurationChanges: [
        { file: "package.json", path: "scripts.check", value: "biome check ." },
        {
          file: "package.json",
          path: "scripts.format:biome",
          value: "biome format --write .",
        },
      ],
    },
  ),
  selectedFeature(
    "content:none",
    (configuration) => configuration.content.setup === "none",
  ),
  selectedFeature(
    "content:markdown",
    (configuration) => configuration.content.setup === "markdown",
    {
      templates: [
        contentConfigTemplate,
        {
          destination: "src/content/posts/getting-started.md",
          content:
            "---\ntitle: Getting started\ndescription: Your first Markdown post.\n---\n\n# Getting started\n\nStart writing in Markdown. This entry is available through Astro's content layer.\n",
        },
      ],
    },
  ),
  selectedFeature(
    "content:mdx",
    (configuration) => configuration.content.setup === "mdx",
    {
      dependencies: [
        { name: "@astrojs/mdx", version: "^7.0.2", type: "devDependency" },
      ],
      templates: [
        contentConfigTemplate,
        {
          destination: "src/content/posts/getting-started.mdx",
          content:
            "---\ntitle: Getting started\ndescription: Your first MDX post.\n---\n\n# Getting started\n\nYou can use **Markdown** and {`JavaScript expressions`} in this page.\n",
        },
      ],
      configurationChanges: [
        {
          file: "astro.config.mjs",
          path: "integrations",
          value: { type: "astro-config-expression", code: "[mdx()]" },
          imports: ['import mdx from "@astrojs/mdx";'],
        },
      ],
    },
  ),
  selectedFeature(
    "content:collections",
    (configuration) => configuration.content.setup === "collections",
    {
      templates: [
        contentConfigTemplate,
        {
          destination: "src/content/posts/getting-started.md",
          content:
            "---\ntitle: Getting started\ndescription: Your first content collection entry.\n---\n\n# Getting started\n\nThis entry is loaded through Astro's content layer.\n",
        },
      ],
    },
  ),
  selectedFeature(
    "forms:none",
    (configuration) => configuration.features.forms === "none",
  ),
  selectedFeature(
    "forms:resend",
    (configuration) => configuration.features.forms === "resend",
    {
      validate: (configuration) =>
        configuration.deployment.target === "static"
          ? [
              selectionIssue(
                "resend-requires-server-runtime",
                "features.forms",
                "Resend requires a server-capable deployment target and cannot be used with static output.",
                "Choose Vercel, Netlify, or Cloudflare, or remove the Resend integration.",
              ),
            ]
          : [],
      dependencies: [
        { name: "resend", version: "^6.17.2", type: "dependency" },
      ],
      templates: [
        contactFormTemplate,
        {
          destination: ".env.example",
          content:
            "# Create a sending-only API key and verify the sender domain in Resend.\nRESEND_API_KEY=re_your_api_key\nRESEND_FROM_EMAIL=contact@your-domain.com\nRESEND_TO_EMAIL=you@your-domain.com\n",
        },
        {
          destination: "src/pages/api/contact.ts",
          content: `import type { APIRoute } from "astro";\nimport { Resend } from "resend";\n\nconst value = (formData: FormData, key: string): string => {\n  const entry = formData.get(key);\n  return typeof entry === "string" ? entry.trim() : "";\n};\n\nexport const POST: APIRoute = async ({ request }) => {\n  const formData = await request.formData();\n  const name = value(formData, "name");\n  const email = value(formData, "email");\n  const message = value(formData, "message");\n\n  if (!email || !message)\n    return new Response(JSON.stringify({ error: "Email and message are required." }), {\n      status: 400,\n      headers: { "Content-Type": "application/json" },\n    });\n\n  const apiKey = import.meta.env.RESEND_API_KEY;\n  const from = import.meta.env.RESEND_FROM_EMAIL;\n  const to = import.meta.env.RESEND_TO_EMAIL;\n  if (!apiKey || !from || !to)\n    return new Response(JSON.stringify({ error: "Email delivery is not configured." }), {\n      status: 500,\n      headers: { "Content-Type": "application/json" },\n    });\n\n  const { error } = await new Resend(apiKey).emails.send({\n    from,\n    to: [to],\n    subject: \`New contact form message from \${name || email}\`,\n    replyTo: email,\n    text: \`Name: \${name || "Not provided"}\\nEmail: \${email}\\n\\n\${message}\`,\n  });\n  if (error)\n    return new Response(JSON.stringify({ error: "Unable to send the message." }), {\n      status: 502,\n      headers: { "Content-Type": "application/json" },\n    });\n\n  return new Response(JSON.stringify({ ok: true }), {\n    status: 200,\n    headers: { "Content-Type": "application/json" },\n  });\n};\n`,
        },
      ],
      configurationChanges: [
        { file: "astro.config.mjs", path: "output", value: "server" },
      ],
    },
  ),
  selectedFeature(
    "forms:webhooks",
    (configuration) => configuration.features.forms === "webhooks",
    {
      validate: (configuration) =>
        configuration.deployment.target === "static"
          ? [
              selectionIssue(
                "webhooks-require-server-runtime",
                "features.forms",
                "Webhook forwarding requires a server-capable deployment target and cannot be used with static output.",
                "Choose Vercel, Netlify, or Cloudflare, or remove the webhook integration.",
              ),
            ]
          : [],
      templates: [
        contactFormTemplate,
        {
          destination: ".env.example",
          content:
            "# URL that will receive contact form submissions. Keep it private.\nWEBHOOK_URL=https://example.com/contact-webhook\n",
        },
        {
          destination: "src/pages/api/contact.ts",
          content:
            'import type { APIRoute } from "astro";\n\nconst value = (formData: FormData, key: string): string => {\n  const entry = formData.get(key);\n  return typeof entry === "string" ? entry.trim() : "";\n};\n\nexport const POST: APIRoute = async ({ request }) => {\n  const formData = await request.formData();\n  const email = value(formData, "email");\n  const message = value(formData, "message");\n  if (!email || !message)\n    return new Response(JSON.stringify({ error: "Email and message are required." }), {\n      status: 400,\n      headers: { "Content-Type": "application/json" },\n    });\n\n  const webhookUrl = import.meta.env.WEBHOOK_URL;\n  if (!webhookUrl)\n    return new Response(JSON.stringify({ error: "Webhook delivery is not configured." }), {\n      status: 500,\n      headers: { "Content-Type": "application/json" },\n    });\n\n  const response = await fetch(webhookUrl, {\n    method: "POST",\n    headers: { "Content-Type": "application/json" },\n    body: JSON.stringify({\n      name: value(formData, "name"),\n      email,\n      message,\n    }),\n  });\n  if (!response.ok)\n    return new Response(JSON.stringify({ error: "Unable to deliver the message." }), {\n      status: 502,\n      headers: { "Content-Type": "application/json" },\n    });\n\n  return new Response(JSON.stringify({ ok: true }), {\n    status: 200,\n    headers: { "Content-Type": "application/json" },\n  });\n};\n',
        },
      ],
      configurationChanges: [
        { file: "astro.config.mjs", path: "output", value: "server" },
      ],
    },
  ),
  selectedFeature(
    "deployment:static",
    (configuration) => configuration.deployment.target === "static",
    {
      configurationChanges: [
        { file: "astro.config.mjs", path: "output", value: "static" },
      ],
    },
  ),
  selectedFeature(
    "deployment:vercel",
    (configuration) => configuration.deployment.target === "vercel",
    {
      dependencies: [
        { name: "@astrojs/vercel", version: "^11.0.2", type: "devDependency" },
      ],
      configurationChanges: [
        {
          file: "astro.config.mjs",
          path: "adapter",
          value: { type: "astro-config-expression", code: "vercel()" },
          imports: ['import vercel from "@astrojs/vercel";'],
        },
        { file: "astro.config.mjs", path: "output", value: "server" },
      ],
    },
  ),
  selectedFeature(
    "deployment:netlify",
    (configuration) => configuration.deployment.target === "netlify",
    {
      dependencies: [
        { name: "@astrojs/netlify", version: "^8.1.1", type: "devDependency" },
      ],
      configurationChanges: [
        {
          file: "astro.config.mjs",
          path: "adapter",
          value: { type: "astro-config-expression", code: "netlify()" },
          imports: ['import netlify from "@astrojs/netlify";'],
        },
        { file: "astro.config.mjs", path: "output", value: "server" },
      ],
    },
  ),
  selectedFeature(
    "deployment:cloudflare",
    (configuration) => configuration.deployment.target === "cloudflare",
    {
      dependencies: [
        {
          name: "@astrojs/cloudflare",
          version: "^14.1.2",
          type: "devDependency",
        },
        { name: "wrangler", version: "^4.110.0", type: "devDependency" },
      ],
      configurationChanges: [
        {
          file: "astro.config.mjs",
          path: "adapter",
          value: { type: "astro-config-expression", code: "cloudflare()" },
          imports: ['import cloudflare from "@astrojs/cloudflare";'],
        },
        { file: "astro.config.mjs", path: "output", value: "server" },
      ],
    },
  ),
];

function stableFeatureOrder(
  features: readonly FeatureDefinition[],
): FeatureDefinition[] {
  return [...features].sort((left, right) => left.id.localeCompare(right.id));
}

function addConflict(
  conflicts: FeatureConflict[],
  kind: FeatureConflict["kind"],
  target: string,
  featureIds: readonly string[],
): void {
  conflicts.push({
    kind,
    target,
    featureIds: [...featureIds].sort(),
    message: `Features ${[...featureIds].sort().join(", ")} both change ${target}.`,
  });
}

function sameValue(left: unknown, right: unknown): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

/**
 * Resolves selected features into a deterministic, generator-ready plan.
 * Conflicts are reported before any filesystem work begins.
 */
export function resolveFeatures(
  configuration: ProjectConfiguration,
  registry: readonly FeatureDefinition[] = featureRegistry,
): FeatureResolution {
  const features = stableFeatureOrder(
    registry.filter((feature) => feature.isSelected(configuration)),
  );
  const dependencies: FeatureDependency[] = [];
  const templates: FeatureTemplate[] = [];
  const configurationChanges: FeatureConfigurationChange[] = [];
  const hooks: {
    feature: FeatureDefinition;
    hooks: FeatureLifecycleHooks;
  }[] = [];
  const errors: ConfigurationIssue[] = [];
  const conflicts: FeatureConflict[] = [];
  const files = new Map<string, string>();
  const changes = new Map<string, { featureId: string; value: unknown }>();
  const packages = new Map<
    string,
    { featureId: string; dependency: FeatureDependency }
  >();

  for (const feature of features) {
    errors.push(...(feature.validate?.(configuration) ?? []));
    const featureTemplates =
      typeof feature.templates === "function"
        ? feature.templates(configuration)
        : (feature.templates ?? []);
    for (const template of featureTemplates) {
      const owner = files.get(template.destination);
      if (owner)
        addConflict(conflicts, "file", template.destination, [
          owner,
          feature.id,
        ]);
      else files.set(template.destination, feature.id);
      templates.push(template);
    }
    for (const change of feature.configurationChanges ?? []) {
      const key = `${change.file}:${change.path}`;
      const existing = changes.get(key);
      if (existing && !sameValue(existing.value, change.value)) {
        addConflict(conflicts, "configuration", key, [
          existing.featureId,
          feature.id,
        ]);
      } else if (!existing)
        changes.set(key, { featureId: feature.id, value: change.value });
      configurationChanges.push(change);
    }
    for (const dependency of feature.dependencies ?? []) {
      const existing = packages.get(dependency.name);
      if (
        existing &&
        (existing.dependency.version !== dependency.version ||
          existing.dependency.type !== dependency.type)
      ) {
        addConflict(conflicts, "dependency", dependency.name, [
          existing.featureId,
          feature.id,
        ]);
      } else if (!existing) {
        packages.set(dependency.name, { featureId: feature.id, dependency });
        dependencies.push(dependency);
      }
    }
    if (feature.hooks) hooks.push({ feature, hooks: feature.hooks });
  }

  return {
    features,
    dependencies,
    templates,
    configurationChanges,
    hooks,
    errors,
    conflicts,
    valid: errors.length === 0 && conflicts.length === 0,
  };
}
