import { spawn } from "node:child_process";
import { chmod, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import {
  type PackageManager,
  type ProjectConfiguration,
  runProjectScript,
} from "@astro-stack/utils";

export interface Command {
  command: string;
  arguments: readonly string[];
}

export type CommandRunner = (
  command: Command,
  directory: string,
) => Promise<void>;

export class InstallationError extends Error {
  constructor(
    readonly command: Command,
    cause: unknown,
  ) {
    super(
      `Could not run ${[command.command, ...command.arguments].join(" ")}: ${cause instanceof Error ? cause.message : String(cause)}`,
      { cause },
    );
    this.name = "InstallationError";
  }
}

const installCommands: Readonly<Record<PackageManager, Command>> = {
  npm: { command: "npm", arguments: ["install"] },
  pnpm: { command: "pnpm", arguments: ["install"] },
  yarn: { command: "yarn", arguments: ["install"] },
  bun: { command: "bun", arguments: ["install"] },
};

/** Executes a command without inheriting interactive input from the generator. */
export async function runCommand(
  command: Command,
  directory: string,
): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command.command, command.arguments, {
      cwd: directory,
      stdio: ["ignore", "inherit", "inherit"],
    });
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (code === 0) resolve();
      else
        reject(
          new Error(
            signal ? `terminated by ${signal}` : `exited with code ${code}`,
          ),
        );
    });
  });
}

/** Installs dependencies (and therefore creates the selected manager's lockfile). */
export async function installDependencies(
  configuration: ProjectConfiguration,
  directory: string,
  runner: CommandRunner = runCommand,
): Promise<void> {
  const command = installCommands[configuration.project.packageManager];
  try {
    await runner(command, directory);
  } catch (error) {
    throw new InstallationError(command, error);
  }
}

/** Initializes a repository for generated projects when requested. */
export async function initializeGit(
  directory: string,
  runner: CommandRunner = runCommand,
): Promise<void> {
  const command: Command = { command: "git", arguments: ["init"] };
  try {
    await runner(command, directory);
  } catch (error) {
    throw new InstallationError(command, error);
  }
}

/** Installs a project-owned pre-commit hook after Git initialization succeeds. */
export async function installPreCommitHook(
  configuration: ProjectConfiguration,
  directory: string,
): Promise<void> {
  const hookDirectory = join(directory, ".git", "hooks");
  const scripts = [
    ...(configuration.styling.prettier ? ["format"] : []),
    ...(configuration.styling.biome ? ["format:biome"] : []),
    ...(configuration.styling.eslint ? ["lint:fix"] : []),
    "typecheck",
  ];
  const content = `#!/bin/sh\n# Generated by Astro Stack. Edit this project-owned hook as needed.\nset -eu\n\n${scripts
    .map((script) =>
      runProjectScript(configuration.project.packageManager, script),
    )
    .join("\n")}\n`;
  try {
    await mkdir(hookDirectory, { recursive: true });
    const hook = join(hookDirectory, "pre-commit");
    await writeFile(hook, content, "utf8");
    await chmod(hook, 0o755);
  } catch (error) {
    throw new Error(
      `Could not install the pre-commit hook: ${error instanceof Error ? error.message : String(error)}. Fix the issue, then recreate .git/hooks/pre-commit using the project's format, lint:fix, and typecheck commands.`,
      { cause: error },
    );
  }
}

export interface ProjectFinishResult {
  /**
   * Whether dependency installation completed. Git initialization and the
   * pre-commit hook are local operations that always complete or throw, so a
   * failed install is the only partial outcome the caller must recover from.
   */
  dependenciesInstalled: boolean;
  installError?: InstallationError;
}

/**
 * Completes post-generation setup after the project directory has been written.
 *
 * Git initialization and the pre-commit hook are local, reliable steps, so they
 * run before dependency installation reaches the network. That ordering means a
 * failed install (offline, a peer-dependency conflict, ...) never discards the
 * generated repository or its hooks; the failure is reported for recovery
 * instead.
 */
export async function finishProject(
  configuration: ProjectConfiguration,
  directory: string,
  runner: CommandRunner = runCommand,
): Promise<ProjectFinishResult> {
  if (configuration.project.initializeGit)
    await initializeGit(directory, runner);
  if (configuration.developerExperience.hooks)
    await installPreCommitHook(configuration, directory);
  try {
    await installDependencies(configuration, directory, runner);
    return { dependenciesInstalled: true };
  } catch (error) {
    if (error instanceof InstallationError)
      return { dependenciesInstalled: false, installError: error };
    throw error;
  }
}
